# Copyright 2025-2026 Joseph Benraz <4public@benraz.com>
# SPDX-License-Identifier: Apache-2.0

"""The launcher bootstrap that prepares .env for the Compose paths.

Two scripts must behave identically -- scripts/ensure-compose-env.sh for the
mac launchers and scripts/ensure-compose-env.ps1 for the Windows ones -- because
a quickstart that generates a credential on one platform and a well-known
default on the other is the bug this whole mechanism exists to prevent.

Both are parameterised over the same assertions. The PowerShell case runs
wherever pwsh exists and skips elsewhere; CI installs it so the Windows path is
covered on every change.
"""

import os
import re
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]

# Generated by the scripts: a 32-byte value rendered as 64 hex characters.
GENERATED = {
    "LITELLM_MASTER_KEY": re.compile(r"^sk-[0-9a-f]{64}$"),
    "POSTGRES_PASSWORD": re.compile(r"^[0-9a-f]{64}$"),
}

# Values that must never survive bootstrap, whatever the example file says.
KNOWN_DEFAULTS = {"sk-1234", "postgres", ""}

def _runners():
    """Every interpreter that can run a bootstrap script here.

    Both PowerShells are exercised where present. `powershell` matters most:
    that is what start-*-windows.bat invokes, and it is Windows PowerShell 5.1
    on .NET Framework, whose API surface is narrower than pwsh 7's.
    """
    found = []

    bash = shutil.which("bash")
    found.append(
        pytest.param(
            ("sh", bash),
            id="posix",
            marks=pytest.mark.skipif(bash is None, reason="bash not installed"),
        )
    )

    shells = [(name, shutil.which(name)) for name in ("pwsh", "powershell")]
    if not any(path for _, path in shells):
        return found + [
            pytest.param(
                ("ps1", None),
                id="powershell",
                marks=pytest.mark.skip(reason="PowerShell not installed"),
            )
        ]

    return found + [
        pytest.param(("ps1", path), id=name) for name, path in shells if path
    ]


SCRIPTS = _runners()


@pytest.fixture
def clone(tmp_path):
    """A fresh checkout as a user would have it: examples only, no .env."""
    for relative in (
        ".env.example",
        "src/.env/docker/.env.example",
        "scripts/ensure-compose-env.sh",
        "scripts/ensure-compose-env.ps1",
    ):
        target = tmp_path / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(REPO / relative, target)
    return tmp_path


def bootstrap(clone: Path, runner):
    flavour, executable = runner
    if flavour == "sh":
        command = [executable, str(clone / "scripts/ensure-compose-env.sh")]
    else:
        command = [
            executable,
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            str(clone / "scripts/ensure-compose-env.ps1"),
        ]

    result = subprocess.run(command, capture_output=True, text=True, cwd=clone)
    assert result.returncode == 0, f"bootstrap failed:\n{result.stdout}\n{result.stderr}"
    return result


def read_env(clone: Path) -> dict:
    values = {}
    for line in (clone / ".env").read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or "=" not in line:
            continue
        name, _, value = line.partition("=")
        values[name.strip()] = value.strip()
    return values


@pytest.mark.parametrize("runner", SCRIPTS)
def test_bootstrap_creates_both_env_files(clone, runner):
    bootstrap(clone, runner)

    assert (clone / ".env").is_file()
    assert (clone / "src/.env/docker/.env").is_file()


@pytest.mark.parametrize("runner", SCRIPTS)
def test_every_secret_is_generated_not_shipped(clone, runner):
    bootstrap(clone, runner)
    values = read_env(clone)

    for name, pattern in GENERATED.items():
        assert name in values, f"{name} missing from .env"
        assert pattern.match(values[name]), f"{name} is not a generated value: {values[name]!r}"
        assert values[name] not in KNOWN_DEFAULTS


@pytest.mark.parametrize("runner", SCRIPTS)
def test_secrets_differ_between_machines(tmp_path, runner):
    """Two fresh clones must not end up with the same credential."""
    secrets = []
    for name in ("first", "second"):
        clone = tmp_path / name
        clone.mkdir()
        for relative in (
            ".env.example",
            "src/.env/docker/.env.example",
            "scripts/ensure-compose-env.sh",
            "scripts/ensure-compose-env.ps1",
        ):
            target = clone / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(REPO / relative, target)
        bootstrap(clone, runner)
        secrets.append(read_env(clone))

    for name in GENERATED:
        assert secrets[0][name] != secrets[1][name]


@pytest.mark.parametrize("runner", SCRIPTS)
def test_rerunning_keeps_existing_secrets(clone, runner):
    """Regenerating would orphan the data volumes created with the old values."""
    bootstrap(clone, runner)
    before = (clone / ".env").read_bytes()

    bootstrap(clone, runner)

    assert (clone / ".env").read_bytes() == before


@pytest.mark.parametrize("runner", SCRIPTS)
def test_generated_env_is_utf8_without_bom_and_lf(clone, runner):
    """Compose parses .env itself: a BOM joins the first name, a CR the value."""
    bootstrap(clone, runner)
    raw = (clone / ".env").read_bytes()

    assert not raw.startswith(b"\xef\xbb\xbf"), "byte-order mark would corrupt the first variable"
    assert b"\r" not in raw, "carriage returns would become part of the values"
    raw.decode("utf-8")


@pytest.mark.parametrize("runner", SCRIPTS)
@pytest.mark.skipif(os.name == "nt", reason="POSIX permission bits")
def test_generated_env_is_not_world_readable(clone, runner):
    bootstrap(clone, runner)

    for relative in (".env", "src/.env/docker/.env"):
        mode = stat.S_IMODE((clone / relative).stat().st_mode)
        assert not mode & (stat.S_IRGRP | stat.S_IROTH), f"{relative} is readable by others"


@pytest.mark.parametrize("runner", SCRIPTS)
@pytest.mark.skipif(os.name != "nt", reason="Windows access control lists")
def test_generated_env_grants_no_access_to_other_principals(clone, runner):
    """The Windows counterpart of the mode check above."""
    bootstrap(clone, runner)

    listing = subprocess.run(
        ["icacls", str(clone / ".env")], capture_output=True, text=True, check=True
    ).stdout

    for principal in ("Everyone", "BUILTIN\\Users", "Authenticated Users"):
        assert principal not in listing, f"{principal} can read the generated .env:\n{listing}"


@pytest.mark.parametrize("runner", SCRIPTS)
def test_user_supplied_secret_is_preserved(clone, runner):
    """An operator pointing at their own gateway must not be overwritten."""
    env = clone / ".env"
    shutil.copy2(clone / ".env.example", env)
    env.write_text(
        env.read_text(encoding="utf-8").replace(
            "LITELLM_MASTER_KEY=\n", "LITELLM_MASTER_KEY=sk-operator-supplied\n"
        ),
        encoding="utf-8",
    )

    bootstrap(clone, runner)

    assert read_env(clone)["LITELLM_MASTER_KEY"] == "sk-operator-supplied"


def test_examples_ship_no_usable_credential():
    """The tracked examples are what a fresh clone starts from."""
    text = (REPO / ".env.example").read_text(encoding="utf-8")

    for name in GENERATED:
        assert re.search(rf"^{name}=\s*$", text, re.M), (
            f"{name} must ship empty in .env.example, or bootstrap treats the "
            f"shipped value as operator-supplied and never generates one"
        )
